# tasks file for roles/common

- name: update all of the installed packages
  yum:
    name: "*"
    state: "latest"

- name: install the apache packages
  yum:
    name: "{{ item }}"
    state: "installed"
  with_items: "{{ apache_packages }}"
